### ISSUE TITLE
Investigate onSyncDone issue

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#274]
Investigate onSyncDone behavior in different browsers and when cleared cache.

**Comment by zachferland** [comment]
@michaelsena @oznekenzo any recent info on this? have you still seen this frequently in production? how often? @oznekenzo can't remember or not, have you seen this in the example dapp? how sure we are we that onsync done is not called and it not another un caught bug ? particularly concerned about any specific browser ?

Think i asked some of these things before, but gathering all info before i look into it more? i have not been able to recreate once yet in the example

**Comment by oznekenzo** [comment]
@zachferland 
To be clear - this is different from the other onSyncDone issue (not happening on the second openBox).
No - I have not seen this for a few days Zach.  But didn't you say that this went away because you cleared memory or something on the pinning server?

**Comment by zachferland** [comment]
yeah got the other issue, gonna fix that one, but not too concerning. But yeah trying to distinguish it from all the issues, since we used "must be and onsyncdone issue" a lot the least week or two for everything that was slow or didn't load ahah. 

The issue you mention is not onsyncdone specifically it was just not connecting to the pinning server, which is different. 

But other recent fixes may have resolved most of the issues with specifically onsyncdone. So i wonder if anyone is still seeing it. 

Let me know if it comes up again
