### ISSUE TITLE
Why doesn't onSyncDone return a Promise?

### ISSUE THREAD

**Issue by monkybrain** [3box/3box-js#288]
Hi! I'm curious as to why `onSyncDone` doesn't return a promise? It's the only situation I've found where I have to use a callback instead of `async/await`, which makes the code a bit messy. Would be nice to able to initiate the interaction with 3box in the following way:

```javascript
const box = await.openBox('0x...')
await box.onSyncDone()
```

I suspect it's because `onSyncDone` is more of an event listener than an async operation. But still think it would be a nice feature :-)

**Comment by monkybrain** [comment]
For the record, to get the behaviour described above, I wrapped `onSyncDone` myself in a promise like this:

```javascript
const onSyncDone = (box) => {
  return new Promise( (resolve, reject) => {
    box.onSyncDone( () => resolve() )
  })
}
```

**Comment by oed** [comment]
Thanks for the question @monkybrain! The main reason is that you might want to have some functionality that executes when the box finishes syncing. For example, you probably want to render your app directly after `openBox` and then after updates have been synced from the network you'd likely want to re-render your app. This makes the UX better for the user since they don't have to wait for all data to be synced from the network if there is only a small amount of data that needs to be synced. 

This could of course also be possible with a promise, but would be more difficult to implement.

**Comment by monkybrain** [comment]
Ok, thanks for the explanation!
