### ISSUE TITLE
Significant Delay in Sync

### ISSUE THREAD

**Issue by crusyn** [3box/3box-js#308]
**Describe the bug**
We are using 3Box to store profile information about artists on our NFT platform.  We are allowing artists to update their data and have been testing with some success.  We have noticed that is can take many hours for data to sync to the network even when using box.OnSyncDone() before setting values to keys in the store.  This would be frustrating for users because they may update some profile data and then reload the page or go to https://3box.io/address to find that their profile has not been updated.

**To Reproduce**
    let box;
    let logentries;
    Box.openBox(artist.id, window.web3.currentProvider)
      .then(res => (box = res))
      .then(res => box.onSyncDone())
      .then(res => box.public.set("name", artist.name))
      .then(res => box.public.set("affiliation", artist.affiliation))
      .then(res => box.public.set("styleTags", artist.styleTags))
      .then(res => box.public.set("desc", artist.desc))
      .then(res => box.public.get("name"))
      .then(res => console.log(res)) //this contains the updated artist.name value
      .then(res => box.close())
      .then(res => box.logout())
      .then(res => Box.getProfile(artist.id))
      .then(res => console.log(res.name)) //this contains some old artist.name value

Furthermore if we look at box.public.log there are local entries for each new update including updates with their timestamps, but these entries do not show up on https://3box.io/address until some later time.

**Comment by oed** [comment]
Thanks for reporting @crusyn! This does indeed seem like a bug. Does this happen only when you run the code you describe above? When you edit the profile in the 3box.io dapp is the edits directly available?

It seems like you do `box.close` and `box.logout` directly after you set your values. This will close down the connection to the pinning node and the data might not have synced fully. Can you try the same thing but without calling these functions?
Btw, if you call`logout` there is no need to call `close` since logout calls close internally.

**Comment by oed** [comment]
@crusyn Closing this as it seems like the issue occurred because you call `box.close()` right after setting data. 
Feel free to reopen this or create a new issue if you're still having trouble getting it to work. Also feel free to pop into [our discord](https://discord.gg/Z3f3Cxy) for faster feedback 🙂
