### ISSUE TITLE
Can't resolve 'store' module

### ISSUE THREAD

**Issue by kamescg** [3box/3box-js#325]
**Describe the bug**
When installing 3Box the store dependency is not installed.

`Module not found: Can't resolve 'store' in '/Users/admin/Documents/projects/utopia/code/rapid-utopia/node_modules/3box/lib'`

**To Reproduce**
1. Install 3Box using `npm install 3box`

**Expected behavior**
All dependencies installed.

**Comment by zachferland** [comment]
Thanks for reporting @KamesCG! Not seeing the same yet, not sure why it can resolve 'store', we do use it, but it is also listed in our package.json. If you additionally 'npm install store' does it end up working?

**Comment by KamesCG** [comment]
I installed `store` in my root application directory and even copy/pasta the `store` module into the `3box` node_module folder, but still didn't work for some reason @zachferland 

For some reason the `store` module isn't installed, but all other dependencies are...

![No store](https://file.globalupload.io/Dj7pjYtulv.png)

Wiped the `node_module` folder and ran `npm install` just to ensure nothing funny was occuring everything and still receiving the error.

![Terminal](https://file.globalupload.io/AOlXEYgcSD.png)

**Comment by zachferland** [comment]
are you installing from somewhere other than the project root? I would expect npm to flatten the dependency tree and since other modules probably use 'store' I would expect to find it in `yourProjectRoot/node_modules` and not 'yourProjectRoot/node_modules/3box/node_modules/`. If running commands/builds from your project root i would expect npm to resolve the dependency, if ran elsewhere i guess maybe it wouldn't find it, cant say for sure though

**Comment by KamesCG** [comment]
@zachferland I am installing in the root of the project.

I just want to report back I started a completely new application using `create-react-app` and ran into the same issues last night.

**Comment by oed** [comment]
@KamesCG does it say which file is failing to access the "store" dependency?

**Comment by oed** [comment]
@KamesCG have you had a chance to take another look at this? Maybe we should change the localStorage abstraction layer to fix this?
