### ISSUE TITLE
Timestamp metadata from getSpace() && box.public.get() return 13 digit UNIX timestamp, 3Box Activity library returns 10 digit UNIX timestamp

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#396]
Not a bug but should probably be streamlined to one!

**Comment by lsenta** [comment]
Make sense, I believe we have to stick to 10 digit timestamps (seconds) since the activity library relies on the etherscan API that returns 10 digits timestamps.

A question, if we return a timestamps in seconds in metadata, do we want to keep the ms precision and return a floating number: `1556011710.342` or be consistent and round to the nearest / lowest integer?

**Comment by oed** [comment]
I would prefer to do integers!
