### ISSUE TITLE
Create/update 3Box from CLI

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#452]
This is useful is a dev/staker manages their ethereum keys from the CLI, but wants to put information in their profile. Given they don't manage keys on the web, they won't have a UI to edit their profile in the browser, but if an app UI pulls this information into their UI for their address (in like a list view or something), it will be viewable.

Should be able to create a 3Box, update a profile, and update a space.

This would be useful for the Livepeer use case of pro stakers wanting to create a profile, but not sign messages in their web wallet.

**Comment by oed** [comment]
@michaelsena It seems like this would need to be part of the livepeer cli and not 3box.js itself. The livepeer cli would use nodejs to sign messages and update the profile using 3box.js internally. This is unfortunately not something that can be done purely with 3box.js since it wouldn't have access to keys.
