### ISSUE TITLE
Beta lib: Getting error 'invalid encoding at validateBase64' at box.private.log in onSyncDone

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#477]
Was not seeing this prior to updating lib

**Comment by oznekenzo** [comment]
![Screen Shot 2019-06-04 at 5 50 11 PM](https://user-images.githubusercontent.com/8059373/58916268-3b33c680-86f1-11e9-91ea-3f4de5865841.png)

**Comment by oed** [comment]
Somehow a clear text entry was stored in the private store and it failed because it couldn't be decrypted. We removed this entry and got everything working again.

It's unclear how the entry got in there and why it hasn't caused any issues before. Looked like the entry was from oct 2018.

Closing this since we dont' have a good way to further investigate. Let's keep our eyes out for similar issues.
