### ISSUE TITLE
Breaking changes in did-resolver 1.0.0

### ISSUE THREAD

**Issue by liamzebedee** [3box/3box-js#589]
Recently added `did-resolver` as a dependency to `package.json` for ciaodao - turns out it broke `3box-js` usage. This is due to their [breaking changes in 1.0.0](https://github.com/decentralized-identity/did-resolver#breaking-changes-010).

**Comment by oed** [comment]
Thanks for opening this! It's quite a large breaking change, and not super easy to change right now. It might even need some changes in orbitdb because of the way identities are verified in their code (see `3box-orbitdb-plugins`). For now I would recommend just using the previous version of the did-resolver.
