### ISSUE TITLE
Firefox: Error: "Couldn't listen on any of the servers"

### ISSUE THREAD

**Issue by PeterTheOne** [3box/3box-js#682]
**Describe the bug**
Console error `Error: "Couldn't listen on any of the servers"`

**To Reproduce**
Not sure on which function call this happens, but websockets seem to disconnect directly on connection. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 71.0 (64-bit)
 - Version 3box 1.14.0

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser Firefox
 - Version 3box 1.14.0

**Comment by oed** [comment]
I assume that this happens when you call `Box.openBox`? Does this happen every time or just sometimes?

**Comment by PeterTheOne** [comment]
I think it was on `Box.openBox` and it was very consistently happening when I made the report. But when I tried now it worked.

**Comment by dacom-dark-sun** [comment]
This usually happens when a connection is established with the SWARM nodes that are specified through the IPFS config. At the same time, the swarm-nodes do not always respond (strange, but this happens even on private ws-star servers), and therefore, we get an unstable error about the impossibility of establishing a connection.

In order to fix this, the connection to the swarm-nodes must be separated from the main configuration of the IPFS - such as ipfs.swarm.connect()

**Comment by oed** [comment]
Unfortunately this is not possible @dacom-dark-sun. See here: https://github.com/ipfs/js-ipfs/issues/2508

**Comment by nichanank** [comment]
I'm experiencing the same issue on `Box.openBox`. It was working fine yesterday but now I'm getting the `Couldn't listen on any of the servers error`

Is there a known workaround for this? 

![image](https://user-images.githubusercontent.com/15038946/79632612-a7dd7580-818a-11ea-9065-fb6c76c748de.png)

**Desktop**:
OS: MacOS
Browser: Brave 1.5.123
3Box: ^1.17.1

**Comment by oed** [comment]
Looking into if there is a more permanent solve for this!

**Comment by oed** [comment]
Given the information in the issue I linked above it seems like this will be fixed by using https://github.com/libp2p/js-libp2p-stardust once we have updated to the latest version of js-ipfs. We are currently blocked by OrbitDB not supporting the latest ipfs version, but once that is out we can get rid of this issue!

**Comment by oed** [comment]
This issue is solved with the `1.20.0` release!
