### ISSUE TITLE
thread.listMembers() and/or thread.onNewCapabilities() not working

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#703]
After updating library to 1.16.1, in ghostthreads, am not able to get a list of members that are joined in the chat - despite both posting to it in the current session.

This will likely block the release of the updated library in the Chatbox plugin

**Comment by zachferland** [comment]
This was largely fixed in https://github.com/3box/3box-js/commit/ac670d03d930d2c485b70a0f1b35e2cd4833d91c today and some logic changes when you dont auth at open.  

Update chatbox to 1.16.3 or later for fixes

There is some things that can be done in the chatbox to still improve the experience for online ids/profiles. Now with auth later, users are not included in online list until they send a message. We may want to still auth earlier if you know the user wont have to sign a message. Second you probably want to represent num people/peers in room (not just ones who are on line and sent messages, authed at this point now, so doesnt send user join message till then), if not all are authed we could have a total number of peers, then the listmembers still with addresses/name and number of anonymous peers.

**Comment by michaelsena** [comment]
@zachferland to create separate issue for this

**Comment by zachferland** [comment]
Created issued in chatbox for improvements there, closing now
